### ISSUE TITLE
Last year's trouble

### ISSUE THREAD

**Issue by rovonov98** [mehulmpt/empty#2]
Hello,
It's not about this repo, but

You've raised an issue about a year ago with monaco editor on windows, did you manage to fix it? I'm a little bit stuck on it at the moment

https://github.com/CodinGame/monaco-vscode-api/issues/164

**Comment by mehulmpt** [comment]
I think it was fixed updating or something, I forgot exactly what happened there

**Comment by rovonov98** [comment]
Thanks
